[package]
name = "odsr-tui"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.28"
odsr-engine = { workspace = true }
rand = { workspace = true }
ratatui = "0.27"
indexmap = "2.1"
serde_json = "1.0"
